# Generated by Django 4.1.3 on 2022-12-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SqlText',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('gseek_id', models.CharField(max_length=20)),
                ('user', models.CharField(blank=True, max_length=20, null=True)),
                ('host', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sql_text',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('thread', models.CharField(max_length=20)),
                ('user', models.CharField(blank=True, max_length=20, null=True)),
                ('host', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('cnt', models.IntegerField(blank=True, null=True)),
                ('avg', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'state',
                'managed': False,
            },
        ),
    ]
